# Generated by Django 5.1.4 on 2024-12-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_remove_post_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='hii',
            field=models.TextField(default='hii', max_length=300),
        ),
        migrations.AddField(
            model_name='post',
            name='hi',
            field=models.TextField(default='hi', max_length=300),
        ),
    ]
