# Generated by Django 5.1.4 on 2024-12-18 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_user_hi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hi',
        ),
    ]
