# Generated by Django 5.1.4 on 2024-12-28 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_remove_user_hi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
