# Generated by Django 5.1.4 on 2024-12-28 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_post_x_user_y'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='x',
        ),
        migrations.RemoveField(
            model_name='user',
            name='y',
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.TextField(max_length=300, verbose_name='post_content')),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_commmented', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_comments', to='network.post')),
            ],
        ),
    ]
