# Generated by Django 5.1.4 on 2024-12-28 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_remove_post_x_remove_user_y_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
